
export interface Cipher {
  id: string;
  textLocale: string;
  titleKey: string;
  text: string;
  letters: string;
  others?: string;
}


export const CIPHERS: Cipher[] = [
  {
    id: 'exhibition-de',
    textLocale: 'de',
    titleKey: 'CIPHERS.GERMAN_EXHIBITION',
    text: 'CFOC IDLC QYFGGZC NCFQYOCL RFQY WJWDZQY JDR, WJRR TJO RFC OFQYL CFOGJQY HOJQHCO HJOO. WJR FRL KCF RDKRLFLDLFSOR-QYFGGZCO DOW WCZ VFICOCZC-QYFGGZC OFQYL WCZ GJBB. KCF KCFWCO YFBGL CFOC YJCDGFIHCFLRJOJBXRC WCZ VCZPCOWCLCO KDQYRLJKCO FT QYFGGZC-LCML. WJR ICRDQYLC VFCZLC BSCRDOIRPSZL FRL WCZ VSZOJTC "PYFLGFCBW" VSO PYFLGFCBW WFGGFC, CFOCT JTCZFHJOFRQYCO HZXELSIZJGCO, WCZ NDRJTTCO TFL TJZLFO YCBBTJO WCO RS ICOJOOLCO WFGGFC-YCBBTJO-RQYBDCRRCBJDRLJDRQY VSZICRLCBBL YJL. WFCRCR VCZGJYZCO NDT JDRLJDRQY CFOCR ICYCFTCO RQYBDCRRCBR DCKCZ CFOCO OFQYL JKYSCZRFQYCZCO HJOJB PFZW JDQY YCDLC OSQY KCF GJRL ACWCZ VCZKFOWDOI FT FOLCZOCL VCZPCOWCL. NDT RQYBDRR OSQY CFO YFOPCFR GDCZ WCO BCLNLCO RQYZFLL: WJR ICYCFTPSZL WSZL FRL WJR YCFTJLBJOW WCZ ICRDQYLCO HZXELSIZJGFO. RFC RLJTTL JDR WCT IBCFQYCO BJOW PFC WFGGFC DOW YCBBTJO, OJCTBFQY JDR "JTCZFHJ".',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    others: ' .,;:-"',
  },
  {
    id: 'exhibition-en',
    textLocale: 'en',
    titleKey: 'CIPHERS.ENGLISH_EXHIBITION',
    text: 'J ISSW QFEYCZ FR SOC LYJL QJOOSL KC QZJQHCW. GSZ RDKRLFLDLFSO QFEYCZR JOW VFICOCZC QFEYCZR LYFR FR OSL LYC QJRC. KSLY QJO KC JLLJQHCW KX GZCUDCOQX JOJBXRFR SG LYC BCLLCZR DRCW FO LYC QFEYCZ LCML. LYC RCCHCW GSZ GSDZLY PSZW FR LYC GFZRL OJTC "PYFLGFCBW" SG PYFLGFCBW WFGGFC, J JTCZFQJO QZXELSIZJEYCZ PYS QS-FOVCOLCW LYC RS-QJBBCW WFGGFC-YCBBTJO HCX CMQYJOIC LSICLYCZ PFLY TJZLFO YCBBTJO. LYFR TCLYSW QJO KC DRCW LS CMQYJOIC J RCQZCL HCX SVCZ J EDKBFQ QSTTDOFQJLFSO QYJOOCB. FL FR RLFBB DRCW LSWJX FO JBTSRL CVCZX QSOOCQLFSO SVCZ LYC FOLCZOCL. JL BJRL J YFOL GSZ LYC BJRL QSWC: LYC EJRREYZJRC LYCZC FR LYC ICZTJO RECBBFOI SG LYC YSTC QSDOLZX SG LYC RCCHCW QZXELSIZJEYCZ. RYC FR GZST LYC RJTC QSDOLZX JR WFGGFC JOW YCBBTJO. FLR ICZTJO RECBBFOI FR "JTCZFHJ".',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    others: ' .,;:-"',
  },
]
