import { SimpleSubstitution } from "./components/simple-substitution-helper/simple-substitution-helper.component";

export const CODING_SUBS: SimpleSubstitution = [
  ["A", "00"],
  ["B", "01"],
  ["C", "02"],
  ["D", "03"],
  ["E", "04"],
  ["F", "05"],
  ["G", "06"],
  ["H", "07"],
  ["I", "08"],
  ["J", "09"],
  ["K", "10"],
  ["L", "11"],
  ["M", "12"],
  ["N", "13"],
  ["O", "14"],
  ["P", "15"],
  ["Q", "16"],
  ["R", "17"],
  ["S", "18"],
  ["T", "19"],
  ["U", "20"],
  ["V", "21"],
  ["W", "22"],
  ["X", "23"],
  ["Y", "24"],
  ["Z", "25"],
];

export const CAESAR_SUBS: SimpleSubstitution = [
  ["X", "A"],
  ["Y", "B"],
  ["Z", "C"],
  ["A", "D"],
  ["B", "E"],
  ["C", "F"],
  ["D", "G"],
  ["E", "H"],
  ["F", "I"],
  ["G", "J"],
  ["H", "K"],
  ["I", "L"],
  ["J", "M"],
  ["K", "N"],
  ["L", "O"],
  ["M", "P"],
  ["N", "Q"],
  ["O", "R"],
  ["P", "S"],
  ["Q", "T"],
  ["R", "U"],
  ["S", "V"],
  ["T", "W"],
  ["U", "X"],
  ["V", "Y"],
  ["W", "Z"],
];

export const ROT13_SUBS: SimpleSubstitution = [
  ["N", "A"],
  ["O", "B"],
  ["P", "C"],
  ["Q", "D"],
  ["R", "E"],
  ["S", "F"],
  ["T", "G"],
  ["U", "H"],
  ["V", "I"],
  ["W", "J"],
  ["X", "K"],
  ["Y", "L"],
  ["Z", "M"],
  ["A", "N"],
  ["B", "O"],
  ["C", "P"],
  ["D", "Q"],
  ["E", "R"],
  ["F", "S"],
  ["G", "T"],
  ["H", "U"],
  ["I", "V"],
  ["J", "W"],
  ["K", "X"],
  ["L", "Y"],
  ["M", "Z"],
];
