name: Test Angular app
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - main
  pull_request:
  # Run CI once per day (at 06:00 UTC)
  schedule:
    - cron: '0 6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci

      - name: Build
        run: ./node_modules/.bin/ng build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci

      - name: Lint
        run: ./node_modules/.bin/ng lint

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci

      - name: Run unit tests
        run: ./node_modules/.bin/ng test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
